stages:
  - build-and-test
  - benchmark
  - full-test

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_BIN: /home/gitlab-runner/.local/graal-core/bin/java
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse/eclipse

before_script:
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - ant -Dskip.graal=true checkstyle
    - ant -Dskip.graal=true eclipseformat-check
    - timeout 5m ant -Dskip.graal=true unit-tests som-tests

kompos_and_dym_tests:
  stage: full-test
  tags: [benchmarks, infinity]
  script:
    - ant -Dskip.graal=true jacoco-lib compile dynamic-metrics-tests superinstructions-tests
    - cd tools/kompos && npm install . && npm -s run verify && npm test

replay_tests:
  stage: full-test
  tags: [benchmarks, infinity]
  script:
    - timeout 10m ant -Dskip.graal=true replay-tests


benchmark_savina_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ant -Dskip.graal=true compile
    - export EXP=`if [[ "$CI_BUILD_REF_NAME" = "master" ]]; then echo "SOMns-Savina"; else echo "SOMns-Savina-exp"; fi`; rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns-Savina --branch=master codespeed.conf $EXP

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ant -Dskip.graal=true compile
    - export EXP=`if [[ "$CI_BUILD_REF_NAME" = "master" ]]; then echo "SOMns"; else echo "SOMns-exp"; fi`; rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns --branch=master codespeed.conf $EXP

benchmark_interp_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ant -Dskip.graal=true compile
    - export EXP=`if [[ "$CI_BUILD_REF_NAME" = "master" ]]; then echo "SOMns-interp"; else echo "SOMns-interp-exp"; fi`; rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns --branch=master codespeed.conf $EXP

benchmark_nightly_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  only:
    - triggers
  script:
    - ant -Dskip.graal=true compile
    - rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns --branch=master codespeed.conf nightly
    - rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns --branch=master codespeed.conf SOMns-Savina-tracing
